NetCommunitySolution.Web/Areas/Admin/Models/Customers/CustomerListModel.cs
namespace NetCommunitySolution.Web.Areas.Admin.Models.Customers
{
    public class CustomerListModel
    {
        /// <summary>
        /// 关键字
        /// </summary>
        public string Keywords { get; set; }

        /// <summary>
        /// 是否代理商
        /// </summary>
        public bool? IsAgent { get; set; }

        
    }
}

NetCommunitySolution.Web/Areas/Admin/Controllers/CustomerController.cs
using Abp.AutoMapper;
using NetCommunitySolution.Common;
using NetCommunitySolution.Customers;
using NetCommunitySolution.Domain.Configuration;
using NetCommunitySolution.Domain.Customers;
using NetCommunitySolution.Security;
using NetCommunitySolution.Web.Areas.Admin.Models.Customers;
using NetCommunitySolution.Web.Framework.Layui;
using System.Linq;
using System.Web.Mvc;

namespace NetCommunitySolution.Web.Areas.Admin.Controllers
{
    public class CustomerController : AdminBaseController
    {
        #region ctor && Fields
        private readonly ICustomerService _customerService;
        private readonly IEncryptionService _encryptionService;
        private readonly ICustomerAttributeService _attributeService;
        private readonly IYeeSevice _yeeService;
        private readonly AccountSetting rateSetting;

        public CustomerController(ICustomerService customerService,
            ICustomerAttributeService attributeService,
            IEncryptionService encryptionService,
            IYeeSevice yeeService,
            ISettingService settingService)
        {
            this._customerService = customerService;
            this._attributeService = attributeService;
            this.rateSetting = settingService.GetAccountSettings();
            this._yeeService = yeeService;
            this._encryptionService = encryptionService;
        }
        #endregion

        #region Utilities
        [NonAction]
        protected void PrepareCustomerRateModel(CustomerRateModel model,int customerId)
        {
            if (model == null)
                model = new CustomerRateModel();
            var customer = _customerService.GetCustomerId(customerId);
            var mchId = customer.GetCustomerAttributeValue<int>(CustomerAttributeNames.SysMchId);
            var rateResult = _yeeService.QueryRate(mchId, 1);
            model.Rate = rateResult.rate;
            var payResult = _yeeService.QueryRate(mchId, 3);
            model.Payment = payResult.rate;
            model.MinPayment = rateSetting.Payment;
            model.MinRate = rateSetting.BaseRate;
        }
            #endregion

        #region Method
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult List(DataSourceRequest command, CustomerListModel model)
        {
            var customers = _customerService.GetAllCustomers(keywords: model.Keywords,
                                            isAgent: model.IsAgent,
                                            pageIndex: command.page - 1,
                                            pageSize: command.limit);


            var jsonData = new DataSourceResult
            {
                data = customers.Items.Select(c => new
                {
                    Id = c.Id,
                    NickName = c.NickName,
                    Mobile = c.Mobile,
                    CreateTime = c.CreationTime.ToString("yyyy/MM/dd"),
                }).ToList(),
                count = customers.TotalCount,
            };

            return AbpJson(jsonData);
        }

        public ActionResult Password()
        {
            var model = new CustomerPasswordModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Password(CustomerPasswordModel model)
        {
            var customer = _customerService.GetCustomerId(this.CustomerId);
            var psd = _encryptionService.CreatePasswordHash(model.OldPassword, customer.PasswordSalt);
            if (model.OldPassword != psd)
                ModelState.AddModelError("", "旧密码输入错误");
            if (!model.NewPassword.Equals(model.ConfirmPassword))
                ModelState.AddModelError("", "两次密码输入的不相同");
            if (ModelState.IsValid)
            {
                var newPsd = _encryptionService.CreatePasswordHash(model.NewPassword, customer.PasswordSalt);

                customer.Password = newPsd;
                _customerService.UpdateCustomer(customer);
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }


        /// <summary>
        /// 设置费率
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult SetRate(int id)
        {
            var model = new CustomerRateModel();
            PrepareCustomerRateModel(model, id);
            return View(model);
        }

        [HttpPost]
        public ActionResult SetRate(CustomerRateModel model)
        {
            if (model.Payment < rateSetting.Payment)
                ModelState.AddModelError("", "您设置的单笔费用低于公共费率");
            if (model.Rate < rateSetting.BaseRate * 10)
                ModelState.AddModelError("", "您设置的交易费率低于公共费率");
            
            if (ModelState.IsValid)
            {
                var customer = _customerService.GetCustomerId(model.Id);
                var mchId = customer.GetCustomerAttributeValue<int>(CustomerAttributeNames.SysMchId);
                _yeeService.SetRate(mchId, 1,model.Rate);
                _yeeService.SetRate(mchId, 3, model.Payment);
                return RedirectToAction("Index");
            }
            PrepareCustomerRateModel(model, model.Id);
            return View(model);

        }

        #endregion

        #region Report 

        [ChildActionOnly]
        public ActionResult CustomerReport()
        {
            var count = _attributeService.GetCountByValue(CustomerAttributeNames.Agent, true);
            var model = new CustomerReportModel();
            model.AgentCount = count;
            var customers = _customerService.GetAllCustomers();
            model.CustomerCount = customers.TotalCount;
            return PartialView(model);
        }
        #endregion

        #region 分部视图
        [ChildActionOnly]
        public ActionResult CustomerHeader()
        {
            var customer = _customerService.GetCustomerId(this.CustomerId);
            var model = customer.MapTo<CustomerModel>();
            model.CustomerAvatar = customer.GetCustomerAttributeValue<string>(CustomerAttributeNames.Avatar);
            model.Authentication = customer.GetCustomerAttributeValue<bool>(CustomerAttributeNames.Authentication);
            model.Agent = customer.GetCustomerAttributeValue<bool>(CustomerAttributeNames.Agent);
            model.Account = customer.GetCustomerAttributeValue<decimal>(CustomerAttributeNames.Account);
            model.Promoter = customer.Agent == 0;
            return PartialView(model);
        }


        #endregion

        #region customer Echarts
        [ChildActionOnly]
        public ActionResult CustomerCharts()
        {
            return PartialView();
        }
        #endregion


        #region Status
        [HttpPost]
        public ActionResult CustomerStatus(int customerId) {
            var customer = _customerService.GetCustomerId(customerId);

            var result = _yeeService.MchQuery(customer.GetCustomerAttributeValue<int>(CustomerAttributeNames.SysMchId), customerId);
            return Json(result);
        }
        #endregion

    }
}

NetCommunitySolution.Web/Controllers/OrderController.cs
using Abp.BackgroundJobs;
using Abp.Runtime.Caching;
using NetCommunitySolution.Common;
using NetCommunitySolution.Customers;
using NetCommunitySolution.Domain.Configuration;
using NetCommunitySolution.Domain.Customers;
using NetCommunitySolution.Domain.Orders;
using NetCommunitySolution.Orders;
using NetCommunitySolution.Security;
using NetCommunitySolution.Web.Framework.Controllers;
using NetCommunitySolution.Web.Framework.WeChat;
using NetCommunitySolution.Web.Models.Orders;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Text;
using System.Web.Mvc;

namespace NetCommunitySolution.Web.Controllers
{
    /// <summary>
    /// 订单控制器
    /// </summary>
    [Mobile]
    public class OrderController : WeChatBaseController
    {

        #region ctor && Fields

        private readonly ICacheManager _cacheManager;
        private readonly AccountSetting accountSetting;
        private readonly WechatSetting wechatSetting;
        private readonly IPaymentService _paymentService;
        private readonly IYeeSevice _yeeService;
        private readonly ICustomerService _customerService;
        private readonly ICustomerAttributeService _attributeService;
        private readonly IAccountLogService _logService;
        private readonly IOrderService _orderService;
        private readonly IBackgroundJobManager _backgroundJobManager;
        private readonly IEncryptionService _encryptionService;

        public OrderController(ISettingService _settingService,
            IPaymentService paymentService,
            IYeeSevice yeeService,
            ICustomerAttributeService attributeService,
            ICustomerService customerService,
            IOrderService orderService,
            IAccountLogService logService,
            ICacheManager cacheManager,
            IEncryptionService encryptionService,
            IBackgroundJobManager backgroundJobManager)
        {
            this._cacheManager = cacheManager;
            this._paymentService = paymentService;
            this._customerService = customerService;
            this._orderService = orderService;
            this._attributeService = attributeService;
            this._logService = logService;
            this._encryptionService = encryptionService;
            this._yeeService = yeeService;
            accountSetting = _settingService.GetAccountSettings();
            wechatSetting = _settingService.GetWeChatSettings();

            this._backgroundJobManager = backgroundJobManager;
        }
        #endregion

        #region Utilities   
        [NonAction]
        public bool PaymentValidators(string password)
        {
            var customer = _customerService.GetCustomerId(this.CustomerId);
            var inputPassword = _encryptionService.CreatePasswordHash(password, customer.PasswordSalt);
            var paymentPassword = customer.GetCustomerAttributeValue<string>(CustomerAttributeNames.TransactionPassword);

            return paymentPassword.Equals(inputPassword);
        }

        /// <summary>
        /// 单笔交易额限制
        /// </summary>
        /// <param name="amount"></param>
        /// <returns></returns>
        [NonAction]
        public bool TradeLimit(decimal amount)
        {
            var limit = true;

            if (amount <= 0)
                limit = false;

            if (accountSetting.TradeLimit)
            {
                if (amount > accountSetting.MaxTrade)
                    return false;
                if (amount < accountSetting.MinTrade)
                    return false;
            }
            return limit;
        }


        private void PrepareWithdrawalsModel(WithdrawalModel model)
        {
            var customer = _customerService.GetCustomerId(this.CustomerId);
            var agent = customer.GetCustomerAttributeValue<bool>(CustomerAttributeNames.Agent);
            model.IsAgent = agent;
            model.MaxTotal = customer.GetCustomerAttributeValue<decimal>(CustomerAttributeNames.Account);
            model.MinTotal = 0m;
        }

        private void PrepareYeePaymentModel(YeePaymentModel model)
        {
            var customer = _customerService.GetCustomerId(this.CustomerId);
            var yeeAuth = customer.GetCustomerAttributeValue<bool>(CustomerAttributeNames.YeeAuth);
            var yeeAudit = customer.GetCustomerAttributeValue<bool>(CustomerAttributeNames.YeeAudit);
            var agent = customer.GetCustomerAttributeValue<bool>(CustomerAttributeNames.Agent);
            if (agent)
                model.Rate = accountSetting.VendorRate;
            else if (customer.Agent == 0 && !agent)
                model.Rate = accountSetting.CommonRate;
            else if (customer.Agent != 0 && !agent)
                model.Rate = accountSetting.MemberRate;

            if (customer.CustomerRoleId == (int)CustomerRole.System)
                model.Rate = accountSetting.BaseRate;

            model.PaymentFee = accountSetting.Payment;
            model.IsAuth = yeeAudit && yeeAuth;
        }
        private void PrepareAgentModel(WeChatPaymentModel model)
        {
            model.AppId = wechatSetting.AppId;
            model.Noncestr = CommonHelper.GenerateNonceStr();
            model.TimeStamp = CommonHelper.GetTimeStamp();
            model.CommonRate = accountSetting.MemberRate;
            model.OrderSn = CommonHelper.GenerateOrderSN();
            model.Total = accountSetting.AgencyFee;
            model.Rate = accountSetting.VendorRate;

            var total = FormatTotal(accountSetting.AgencyFee);
            var result = UnifiedOrder(model.Noncestr, "升级为代理商", model.OrderSn, total, model.TimeStamp);
            //var jsApiString = GetJsApiParameters(result, wechatSetting.Key);
            var handler = result.GetJsApiParametersRequest(wechatSetting.Key);
            model.Signature = result["sign"].ToString();
            var jsonData = new
            {
                appId = handler["appId"],
                timeStamp = handler["timeStamp"],
                nonceStr = handler["nonceStr"],
                package = handler["package"],
                signType = handler["signType"],
                paySign = handler["paySign"],
            };
            model.wxJsApiParam = JsonConvert.SerializeObject(jsonData);
        }
        #endregion

        #region Method Yee Pay

        public ActionResult YeePay()
        {
            var model = new YeePaymentModel();
            PrepareYeePaymentModel(model);            
            return View(model);
        }

        [HttpPost]
        public ActionResult YeePay(YeePaymentModel model)
        {
            if (!TradeLimit(model.Total))
                ModelState.AddModelError("", "单笔交易额超出界限");

            if (ModelState.IsValid)
            {
                var customer = _customerService.GetCustomerId(this.CustomerId);
                var order = new Order
                {
                    AgentId = customer.Agent,
                    CustomerId = customer.Id,
                    IsDeleted = false,
                    OrderModeId = (int)AccountMode.Cash,
                    OrderSn = CommonHelper.GenerateOrderSN(),
                    OrderStatusId = (int)OrderStatus.Pending,
                    OrderTotal = model.Total,
                    CreationTime = DateTime.Now,
                };                
                order.Id = _orderService.CreateOrder(order);
                var mchId = customer.GetCustomerAttributeValue<int>(CustomerAttributeNames.SysMchId);
                var result = _yeeService.Payment(mchId, model.Total, order.OrderSn);
                if (result.status == 0)
                {
                    return Redirect(result.url);
                }
                ModelState.AddModelError("", result.msg);

            }
            PrepareYeePaymentModel(model);
            return View(model);

        }
        #endregion

        #region 提现
        public ActionResult Withdrawals()
        {
            var model = new WithdrawalModel();
            PrepareWithdrawalsModel(model);
            return View(model);
        }
        [HttpPost]
        public ActionResult Withdrawals(WithdrawalModel model)
        {
            if (ModelState.IsValid)
            {
                var order = new Order
                {
                    AgentId = 0,
                    CreationTime = DateTime.Now,
                    CustomerId = this.CustomerId,
                    IsDeleted = false,
                    OrderModeId = (int)AccountMode.Extract,
                    OrderSn = CommonHelper.GenerateOrderSN(),
                    OrderTotal = model.Total,
                    OrderStatusId = (int)OrderStatus.Pending,

                };
                _orderService.CreateOrder(order);

                return RedirectToAction("Success", new { msg = "您的提现已经申请，等额审核后自动拨款" });
            }
            PrepareWithdrawalsModel(model);
            return View(model);

        }



        #endregion

        #region success

        public ActionResult Success(string msg)
        {
            return View();
        }
        #endregion

        #region WeChatPay

        public ActionResult Agent()
        {
            var model = new WeChatPaymentModel();
            PrepareAgentModel(model);
            return View(model);
        }
        [HttpPost]
        public ActionResult Agent(WeChatPaymentModel model)
        {
            var customer = _customerService.GetCustomerId(this.CustomerId);

            Order order = new Order
            {
                AgentId = customer.Agent,
                CustomerId = customer.Id,
                CreationTime = DateTime.Now,
                IsDeleted = false,
                OrderModeId = (int)AccountMode.Agent,
                OrderSn = model.OrderSn,
                OrderStatusId = (int)OrderStatus.Pending,
                OrderTotal = accountSetting.AgencyFee,
                Serial = "",
            };

NetCommunitySolution.Web/Views/Customer/Account.cshtml
@{
    Layout = "~/Views/Shared/_TopicLayout.cshtml";
}

<div class="page-account">
    <div class="account-title">
        <div class="account-img">
            <img src="~/images/diamond.png" width="150" />
        </div>
        <div class="account-content">
            <p>账户余额</p>
            <p class="account-balance"><i class="fa fa-rmb">700.00</i></p>
        </div>

        <div class="weui-btn-area">
            <a class="weui-btn weui-btn_primary" href="">佣金日志</a>
            <a class="weui-btn weui-btn_plain-default">提现</a>
        </div>
    </div>
    <div class="weui-footer weui-footer_fixed-bottom">
        <p class="weui-footer__links">
            <a href="@Url.RouteUrl("Topic",new { SeName = "Problem"})" class="weui-footer__link">常见问题</a>
        </p>
        <p class="weui-footer__text">Copyright &copy; 2008-2016 jie-pang</p>
    </div>
</div>

NetCommunitySolution.Web/Views/Customer/AgentCenter.cshtml
@model NetCommunitySolution.Web.Models.Customers.CustomerAgentCenterModel
@{
    Layout = "~/Views/Shared/_TopicLayout.cshtml";
}

<div class="page-security">
    <div class="weui-cells__title">
        推广中心
    </div>
    <div class="weui-panel">
        <div class="weui-panel__bd">
            <div class="weui-media-box weui-media-box_small-appmsg">
                <div class="weui-cells">

                    <a class="weui-cell weui-cell_access" href="@Url.Action("MyCustomerList","Customer")">
                        <div class="weui-cell__bd weui-cell_primary">
                            <p>推广人数</p>
                        </div>
                        <div class="weui-cell__ft" style="font-size: 0">
                            <i class="weui-icon-info-circle"></i>
                            <span style="vertical-align:middle; font-size: 17px;">@Model.CustomerCount</span>

                        </div>

                    </a>
                </div>
            </div>
        </div>
    </div>


    <div class="weui-panel">
        <div class="weui-panel__bd">
            <div class="weui-media-box weui-media-box_small-appmsg">
                <div class="weui-cells">
                    <a class="weui-cell weui-cell_access" href="javascript:;">
                        <div class="weui-cell__bd weui-cell_primary">
                            <p>本月交易额</p>
                        </div>
                        <div class="weui-cell__ft money" style="font-size: 0">
                            <span style="vertical-align:middle; font-size: 17px; color:#f00"><i class="fa fa-rmb"></i>@Model.TotalAmount</span>
                        </div>
                    </a>
                </div>
            </div>
        </div>

    </div>
</div>

NetCommunitySolution.Web/Views/Customer/CustomerAuth.cshtml
@model  NetCommunitySolution.Web.Models.Customers.CustomerAuthModel
@{
    Html.AddTitleParts("我的认证");
    Layout = "~/Views/Shared/_TopicLayout.cshtml";
}
<div class="page-mobile">

    <div id="loadingToast" style="display:none;">
        <div class="weui-mask_transparent"></div>
        <div class="weui-toast">
            <i class="weui-loading weui-icon_toast"></i>
            <p class="weui-toast__content">图片上传中</p>
        </div>
    </div>

    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "weui-cells_form", @id = "auth-form" }))
    {
        @Html.AntiForgeryToken()
        <div class="weui-cells__title">基本信息</div>
        <div class="weui-cell">
            <div class="weui-cell__hd">
                @Html.WELabelFor(model => model.legal_person)
            </div>
            <div class="weui-cell__bd">
                @Html.WETextBoxFor(model => model.legal_person, "真实姓名")
                @Html.ValidationMessageFor(model => model.legal_person)
            </div>
        </div>
        <div class="weui-cell">
            <div class="weui-cell__hd">
                @Html.WELabelFor(model => model.bind_mobile)
            </div>
            <div class="weui-cell__bd">
                @Html.WEEditorFor(model => model.bind_mobile, "手机号,结算卡签约号", "*")
                @Html.ValidationMessageFor(model => model.bind_mobile)
            </div>
        </div>

        <div class="weui-cell">
            <div class="weui-cell__hd">
                @Html.WELabelFor(model => model.id_card)
            </div>
            <div class="weui-cell__bd">
                @Html.WEEditorFor(model => model.id_card, "身份证号,结算卡签约身份证", "*")
                @Html.ValidationMessageFor(model => model.id_card)
            </div>
        </div>

        <div class="weui-cells__title">银行卡信息</div>

        <div class="weui-cell">
            <div class="weui-cell__hd">
                @Html.WELabelFor(model => model.bank_account_number)
            </div>
            <div class="weui-cell__bd">
                @Html.WENumberFor(model => model.bank_account_number, Model.bank_account_number, "结算卡,收款卡卡号")
                @Html.ValidationMessageFor(model => model.bank_account_number)
            </div>
        </div>
        <div class="weui-cell">
            <div class="weui-cell__hd">
                @Html.WELabelFor(model => model.bank_name)
            </div>
            <div class="weui-cell__bd">
                @Html.WEDropDownListFor(model => model.bank_name, Html.GetBankNameList(Model.bank_name))
                @Html.ValidationMessageFor(model => model.bank_name)
            </div>
        </div>

        <div class="weui-cell">
            <div class="weui-cell__hd">
                @Html.WELabelFor(model => model.area_code)
            </div>
            <div class="weui-cell__bd">
                @Html.HiddenFor(model => model.area_code)
                <a href="javascript:;" class="weui-btn weui-btn_default" id="showPicker">开户地区 @Model.area_code</a>
            </div>
        </div>

        <div class="weui-flex">
            <div class="weui-flex__item">
                @Html.EditorFor(model => model.bank_card_photo)
                <p class="placeholder">银行卡</p>
            </div>

            <div class="weui-flex__item">
                @Html.EditorFor(model => model.person_photo)
                <p class="placeholder">手持身份证</p>

            </div>
        </div>
        <div class="weui-flex">
            <div class="weui-flex__item">
                @Html.EditorFor(model => model.id_card_photo)
                <p class="placeholder">身份证正面</p>
            </div>

            <div class="weui-flex__item">
                @Html.EditorFor(model => model.id_card_back_photo)
                <p class="placeholder">身份证反面</p>

            </div>
        </div>
        <div class="weui-btn-area">
            <input type="submit" value="认证" class="weui-btn weui-btn_primary" />
        </div>
    }
</div>

<script type="text/javascript">
    $('#showPicker').on('click', function () {

        weui.picker(@Html.Action("Areas", "Customer"), {            
            onConfirm: function (result) {
                $("#@Html.FieldIdFor(model=>model.area_code)").val(result[2]);
                $("#showPicker").html(result[2])
                }
            });
    });

</script>

NetCommunitySolution.Web/Views/Customer/ExtensionCode.cshtml
@model  NetCommunitySolution.Web.Models.Customers.ExtensionCodeModel
@{
    Html.AddTitleParts("我的推广码");
    Layout = "~/Views/Shared/_TopicLayout.cshtml";
}
<style>
    .page__title{
        margin:40px auto;
        text-align:center;
    }
    .value {
        margin: 10px auto;
    }
</style>
<div class="page">
    <div class="page-extension-code page__hd">

        <h3 class="page__title">我的推广码</h3>
        <div class="weui-cell">
            <div class="weui-cell__hd value">
                @Model.ExtensionCode
            </div>
        </div>
    </div>

</div>

NetCommunitySolution.Web/Views/Customer/Index.cshtml
@model NetCommunitySolution.Web.Models.Customers.CustomerInfoModel
@{
    Html.AddTitleParts("会员中心");
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}


<script type="text/javascript">
    @if (!String.IsNullOrWhiteSpace(ViewBag.Result))
    {
    <text>
        // toast
    $(function () {
        var $toast = $('#toast');

        $toast.fadeIn(100);
        setTimeout(function () {
            $toast.fadeOut(100);
        }, 2000);
    });
    </text>
    }
</script>

<div id="toast" style="display: none;">
    <div class="weui-mask_transparent"></div>
    <div class="weui-toast">
        <i class="weui-icon-success-no-circle weui-icon_toast"></i>
        <p class="weui-toast__content">操作成功</p>
    </div>
</div>
<div class="page-customer-info">
    <div class="customer-info">

        <div class="weui-media-box weui-media-box_appmsg">
            <div class="weui-media-box__hd">
                <img class="weui-media-box__thumb" src="@Model.CustomerAvatar" alt="">
            </div>
            <div class="weui-media-box__bd">
                <p> @Model.NickName</p>
            </div>
            @if (Model.Authentication)
            {
                <div class="weui-media-box abs authen-box">
                    <a href="@Url.Action("CustomerAuth","Customer")">
                        <i class="fa fa-check"></i> 已认证
                    </a>
                </div>
            }
            else
            {<div class="weui-media-box abs authen-box">
                    <a href="@Url.Action("CustomerAuth","Customer")">
                        未实名认证
                    </a>
                </div>
            }
        </div>
    </div>

    @if (Model.Agent)
    {

    <div class="customer-account weui-flex">
        <div class="weui-flex__item">
            <div class="placeholder">
                <p>
                    <span class="value">用户总消费</span>
                    <i class="fa fa-rmb">@Html.Action("Turnover", "Customer")</i>
                </p>
            </div>
        </div>
        <div class="weui-flex__item">
            <div class="placeholder">
                <a href="@Url.RouteUrl("Account")">
                    <span class="value">佣金</span>
                    <i class="fa fa-rmb">@Model.Account</i>
                </a>
            </div>
        </div>
        <div class="weui-flex__item">
            <div class="placeholder">
                <p>
                    <span class="value">我的用户</span>
                    <i class="fa fa-user">@Html.Action("MyCustomers", "Customer")</i>
                </p>
            </div>
        </div>
    </div>

    }
    <div class="weui-grids">

        @if (!Model.Agent)
    {
        <a href="@Url.Action("Agent", "Order")" class="weui-grid">
            <div class="weui-grid__icon">
                <i class="fa fa-user fa-2x"></i>
            </div>
            <p class="weui-grid__label">升级会员</p>
        </a>
}
        @if (!Model.Agent && Model.AgentID == 0)
    {
        <a href="@Url.Action("MyPromoter", "Customer")" class="weui-grid">
            <div class="weui-grid__icon">
                <i class="fa fa-user fa-2x"></i>
            </div>
            <p class="weui-grid__label">关联会员</p>
        </a>

}
        @if (Model.Agent)
    {
        <a href="@Url.Action("Withdrawals", "Order")" class="weui-grid">
            <div class="weui-grid__icon">
                <i class="fa fa-archive fa-2x"></i>
            </div>
            <p class="weui-grid__label">提现</p>
        </a>

}
        <a href="@Url.Action("Security","Customer")" class="weui-grid">
            <div class="weui-grid__icon">
                <i class="fa fa-key fa-fw fa-2x"></i>
            </div>
            <p class="weui-grid__label">安全管理</p>
        </a>
        <a href="@Url.RouteUrl("Payment")" class="weui-grid">
            <div class="weui-grid__icon">
                <i class="fa fa-credit-card-alt fa-2x"></i>
            </div>
            <p class="weui-grid__label">借款</p>
        </a>
        @if (Model.Agent)
    {
        <a href="@Url.Action("MyQRCode","Customer")" class="weui-grid">
            <div class="weui-grid__icon">
                <i class="fa fa-info fa-2x"></i>
            </div>
            <p class="weui-grid__label">我的推广码</p>
        </a>
}
        @*<a href="@Url.RouteUrl("Topic", new { SeName = "help" })" class="weui-grid">*@
            <a href="@Url.Action("TopicBlock","Topic",new {topicId= "3" })" class="weui-grid">
                <div class="weui-grid__icon">
                    <i class="fa fa-info fa-2x"></i>
                </div>
                <p class="weui-grid__label">帮助中心</p>
            </a>

            @*<a href="@Url.RouteUrl("Topic", new { SeName = "aboutus" })" class="weui-grid">
            <div class="weui-grid__icon">1
                <i class="fa fa-font fa-2x"></i>
            </div>
            <p class="weui-grid__label">公司简介</p>
        </a>*@

            @if (Model.Agent)
    {
        <a href="@Url.Action("AgentCenter", "Customer")" class="weui-grid">
            <div class="weui-grid__icon">
                <i class="fa fa-cloud fa-2x"></i>
            </div>
            <p class="weui-grid__label">推广中心</p>
        </a>

}
</div>
</div>

NetCommunitySolution.Web/Views/Customer/MyPromoter.cshtml
@model NetCommunitySolution.Web.Models.Customers.MyPromoterModel
@{
    ViewBag.Title = "管理代理";
    Layout = "~/Views/Shared/_TopicLayout.cshtml";
}

<div class="page-promoter">

    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "weui-cells_form", @id = "promoter-form" }))
    {
        @Html.AntiForgeryToken()



        <div class="weui-cells__title"></div>
        <div class="weui-cell">
            <div class="weui-cell__hd">
                @Html.WELabelFor(model => model.ExtensionCode)
            </div>
            <div class="weui-cell__bd">
                @Html.WEEditorFor(model => model.ExtensionCode, true, "请输入推广码", "推广码格式不正确", "[a-z|A-Z]{10}")
            </div>
        </div>

        <div class="weui-cell">
        </div>
        <div class="weui-btn-area">
            <input type="submit" value="确定" class="weui-btn weui-btn_primary" />
        </div>

    }
</div>